// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package qrcode

import (
	"backend/api/qrcode"
)

type ControllerV1 struct{}

func NewV1() qrcode.IQrcodeV1 {
	return &ControllerV1{}
}
