// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"
)

// drinkAllYouCanPackagesDao is the data access object for the table drink_all_you_can_packages.
// You can define custom methods on it to extend its functionality as needed.
type drinkAllYouCanPackagesDao struct {
	*internal.DrinkAllYouCanPackagesDao
}

var (
	// DrinkAllYouCanPackages is a globally accessible object for table drink_all_you_can_packages operations.
	DrinkAllYouCanPackages = drinkAllYouCanPackagesDao{internal.NewDrinkAllYouCanPackagesDao()}
)

// Add your custom methods and functionality below.
