// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"
)

// orderDao is the data access object for the table order.
// You can define custom methods on it to extend its functionality as needed.
type orderDao struct {
	*internal.OrderDao
}

var (
	// Order is a globally accessible object for table order operations.
	Order = orderDao{internal.NewOrderDao()}
)

// Add your custom methods and functionality below.
