// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"
)

// packageProductsDao is the data access object for the table package_products.
// You can define custom methods on it to extend its functionality as needed.
type packageProductsDao struct {
	*internal.PackageProductsDao
}

var (
	// PackageProducts is a globally accessible object for table package_products operations.
	PackageProducts = packageProductsDao{internal.NewPackageProductsDao()}
)

// Add your custom methods and functionality below.
