// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"
)

// tableQrcodesDao is the data access object for the table table_qrcodes.
// You can define custom methods on it to extend its functionality as needed.
type tableQrcodesDao struct {
	*internal.TableQrcodesDao
}

var (
	// TableQrcodes is a globally accessible object for table table_qrcodes operations.
	TableQrcodes = tableQrcodesDao{internal.NewTableQrcodesDao()}
)

// Add your custom methods and functionality below.
