// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"
)

// tableDao is the data access object for the table table.
// You can define custom methods on it to extend its functionality as needed.
type tableDao struct {
	*internal.TableDao
}

var (
	// Table is a globally accessible object for table table operations.
	Table = tableDao{internal.NewTableDao()}
)

// Add your custom methods and functionality below.
