// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"
)

// userPackagesDao is the data access object for the table user_packages.
// You can define custom methods on it to extend its functionality as needed.
type userPackagesDao struct {
	*internal.UserPackagesDao
}

var (
	// UserPackages is a globally accessible object for table user_packages operations.
	UserPackages = userPackagesDao{internal.NewUserPackagesDao()}
)

// Add your custom methods and functionality below.
