// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package print

import (
	"backend/api/print"
)

type ControllerV1 struct{}

func NewV1() print.IPrintV1 {
	return &ControllerV1{}
}
